## _An example of assignment problem_ 


* Swimmers relay problem. The expected times (in seconds) of six swimmers in individual events are specified in a matrix


* cost[i,j]= Cost of assigning Row i to Column j


* Here swimmers correspond to rows (zero based index) and events to columns (zero based index)

In [1]:
import numpy as np
from scipy.optimize import linear_sum_assignment

In [2]:
cost = np.array([[68, 73, 63, 57], [67, 70, 64,58], [68, 72, 69,55],[67,75,70,59],[71,69,75,57],[69,71,66,59]]);
row_ind, col_ind = linear_sum_assignment(cost);

#col_ind[j] contains the row index assigned to column j, all indices are zero based
#Assignment computed is displayed below
print(row_ind);
print(col_ind);
print("Assignment of swimmers to events");
for k in range(len(col_ind)):
    print("Swimmer " + str(row_ind[k]+1) + "  assigned to Event " + str(col_ind[k]+1) + " (cost i.e. time = " + str(cost[row_ind[k],col_ind[k]]) + ")"); 
    #+1 since python array indices are zero based


costOptimalAssignment = cost[row_ind, col_ind].sum();
print("Overall cost of the optimal assignment = " + str(costOptimalAssignment));


[0 1 2 4]
[2 0 3 1]
Assignment of swimmers to events
Swimmer 1  assigned to Event 3 (cost i.e. time = 63)
Swimmer 2  assigned to Event 1 (cost i.e. time = 67)
Swimmer 3  assigned to Event 4 (cost i.e. time = 55)
Swimmer 5  assigned to Event 2 (cost i.e. time = 69)
Overall cost of the optimal assignment = 254


In [7]:
cost[row_ind, col_ind]

array([63, 67, 55, 69])