## _Max flow example in Pushmeet Kohli's example_

* Hard coded constraints

In [1]:
import numpy as np
from scipy.optimize import linprog
#from numpy.linalg import solve

In [2]:

capacities = np.array([2,9,2,1,5,4]);
numVariables = len(capacities); # Number of design variables = Number of edges

f = -1*np.array([1,1,0,0,0,0]); # Objective function
A_eqFlowCons = np.array([[1,0,-1,1,-1,0],[0,1,1,-1,0,-1]]);
print(A_eqFlowCons)
print("\n")

b_eqFlowCons = np.array([0,0]);
print(b_eqFlowCons)
print("\n")

A_ineq = np.identity(numVariables);
print(A_ineq)
print("\n")

b_ineq = capacities;
print(b_ineq)
print("\n")

res = linprog(f, A_ub=A_ineq,b_ub=b_ineq,A_eq=A_eqFlowCons,b_eq=b_eqFlowCons);
maxFlow = -res.fun;

flows = res.x;
print("Value of max flow through the network = " + str(maxFlow));
print("Flow on each edge");
print(flows);

[[ 1  0 -1  1 -1  0]
 [ 0  1  1 -1  0 -1]]


[0 0]


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


[2 9 2 1 5 4]


Value of max flow through the network = 7.0
Flow on each edge
[2. 5. 0. 1. 3. 4.]
